# Generated by Django 5.1.1 on 2024-09-24 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foundations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.PositiveBigIntegerField(verbose_name='nit')),
                ('name', models.TextField(max_length=50, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('desc', models.TextField(max_length=100, verbose_name='desc')),
                ('logo', models.ImageField(blank=True, upload_to='logos', verbose_name='logo')),
                ('is_active', models.BooleanField(verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=4, verbose_name='tipo_documento')),
                ('document', models.TextField(max_length=20, verbose_name='documento')),
                ('name', models.TextField(max_length=30, verbose_name='nombre')),
                ('lastname', models.TextField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('brthday', models.DateField(verbose_name='cumpleaños')),
                ('enterprise', models.TextField(max_length=30, verbose_name='empresa')),
                ('is_friend', models.BooleanField(verbose_name='amigo')),
                ('id_couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='foundations.users')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_foundation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundations', to='foundations.foundations')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='foundations.users')),
            ],
        ),
    ]
