# Generated by Django 5.1.1 on 2024-09-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('desc', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='type_document',
            field=models.CharField(max_length=5, verbose_name='tipo_documento'),
        ),
    ]
