# Generated by Django 5.1.1 on 2024-09-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0002_typesdocument_alter_users_type_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id_couple',
        ),
        migrations.AlterField(
            model_name='typesdocument',
            name='desc',
            field=models.TextField(max_length=50),
        ),
        migrations.RenameModel(
            old_name='Foundations',
            new_name='Foundation',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.TextField(max_length=20, verbose_name='documento')),
                ('name', models.TextField(max_length=30, verbose_name='nombre')),
                ('lastname', models.TextField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('birthday', models.DateField(verbose_name='cumpleaños')),
                ('enterprise', models.TextField(max_length=30, verbose_name='empresa')),
                ('is_friend', models.BooleanField(verbose_name='amigo')),
                ('id_couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='foundations.user')),
                ('type_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typesdocument', to='foundations.typesdocument')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('id_foundation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundation', to='foundations.foundation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='foundations.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Donations',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
