# Generated by Django 5.1.1 on 2024-09-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0004_user_is_active_alter_foundation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(default='2024-09-26', verbose_name='FechaDonacion'),
            preserve_default=False,
        ),
    ]
