# Generated by Django 5.1.1 on 2024-09-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0006_rol_alter_user_type_document_user_id_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=1, max_length=200, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foundation',
            name='desc',
            field=models.TextField(max_length=100, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='is_active',
            field=models.BooleanField(verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='foundations.user', verbose_name='Pareja'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rol', to='foundations.rol', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoDocumento', to='foundations.typesdocument', verbose_name='Tipo Documento'),
        ),
    ]
