# Generated by Django 5.1.1 on 2024-09-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0007_user_password_alter_foundation_desc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_date',
            field=models.DateField(verbose_name='Fecha Donación'),
        ),
    ]
