# Generated by Django 5.1.1 on 2024-09-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0009_alter_foundation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='nit',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='nit'),
        ),
    ]
