# Generated by Django 5.1.1 on 2024-09-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0010_alter_foundation_is_active_alter_foundation_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.TextField(max_length=20, unique=True, verbose_name='documento'),
        ),
    ]
